import { GlobalStyle } from '@/shared/styles/GlobalStyle';
import { Sidebar } from '@shared/ui';
import { Theme } from '@radix-ui/themes';
import '@shared/styles/globals.css';
import '@radix-ui/themes/styles.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Theme>
          {/* <header style={{ width: '100%' }}>
          </header> */}
          <div id="container" className="flex h-[100vh] w-[100%]">
            <GlobalStyle />
            <aside>
              <Sidebar />
            </aside>
            {children}
          </div>
        </Theme>
      </body>
    </html>
  );
}
